shamefullyHoist: true

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@vuetify/unplugin-styles@1.0.0-rc.1'
  - vuetify-nuxt-module@1.0.0-rc.4
